# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_repos'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='fileName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
