# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_media_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='fileName',
            new_name='name',
        ),
    ]
