# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 03:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_auto_20160508_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='timelineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('message', 'message'), ('file', 'file'), ('system', 'system')], default='message', max_length=50)),
                ('text', models.TextField(max_length=2000, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectsTimelineItems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
