# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettingsfield',
            name='value',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
