# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_auto_20160107_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='haveCss',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='haveJs',
            field=models.BooleanField(default=True),
        ),
    ]
