# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_auto_20160202_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='haveCss',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='haveJs',
            field=models.BooleanField(default=True),
        ),
    ]
