# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_auto_20160206_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='inMenu',
            field=models.BooleanField(default=True),
        ),
    ]
