# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20160109_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='default',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='fieldType',
            field=models.CharField(choices=[('char', 'char'), ('boolean', 'boolean'), ('float', 'float'), ('date', 'date'), ('choice', 'choice')], default='char', max_length=15),
        ),
    ]
