# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20160109_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='unit',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
