# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20160109_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='generictype',
            name='icon',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
