# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_generictype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
