# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20160109_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='link',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaType',
            field=models.CharField(choices=[('onlineVideo', 'onlineVideo'), ('video', 'video'), ('image', 'image'), ('onlineImage', 'onlineImage'), ('doc', 'doc')], default='image', max_length=10),
        ),
    ]
