# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0010_auto_20160110_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('cart', 'cart'), ('wishlist', 'wishlist')], default='cart', max_length=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inCarts', to='ecommerce.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerceCart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.CharField(choices=[('onlineBanking', 'onlineBanking'), ('COD', 'COD'), ('eMoney', 'eMoney')], default='COD', max_length=15),
        ),
        migrations.DeleteModel(
            name='cart',
        ),
    ]
