# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20160110_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zipcode',
            new_name='pincode',
        ),
        migrations.AlterField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerceListings', to=settings.AUTH_USER_MODEL),
        ),
    ]
