# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_auto_20160113_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='mobile',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
