# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_customerprofile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
