# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_auto_20160114_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amountPaid',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
    ]
