# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_auto_20160114_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='choiceLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='choiceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='ecommerce.choiceLabel')),
            ],
        ),
    ]
