# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0023_auto_20160115_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cod', models.BooleanField(default=False)),
                ('freeReturns', models.BooleanField(default=False)),
                ('replacementPeriod', models.PositiveIntegerField(null=True)),
                ('rate', models.PositiveIntegerField(null=True)),
                ('shippingOptions', models.CharField(choices=[('pickup', 'pickup'), ('homeDelivary', 'homeDelivary'), ('postal', 'postal')], default='pickup', max_length=15)),
                ('availability', models.CharField(choices=[('local', 'local'), ('state', 'state'), ('national', 'national'), ('international', 'international')], default='local', max_length=15)),
                ('shippingFee', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='cod',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='freeReturns',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='replacementPeriod',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='shippingOptions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ecommerce.listing'),
        ),
        migrations.AddField(
            model_name='offering',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='ecommerce.service'),
        ),
        migrations.AddField(
            model_name='offering',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerceOfferings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecommerce.offering'),
        ),
    ]
