# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_offering_instock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providerOptions', to='ecommerce.listing'),
        ),
    ]
