# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_auto_20160116_0320'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offering',
            unique_together=set([('service', 'item')]),
        ),
    ]
