# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_auto_20160116_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='startDate',
            field=models.DateTimeField(null=True),
        ),
    ]
