# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_auto_20160117_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='endDate',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='startDate',
            new_name='start',
        ),
    ]
