# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_auto_20160129_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
