# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0034_auto_20160207_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbanner',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
