# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0038_auto_20160214_0424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewdislike',
            old_name='review',
            new_name='parent',
        ),
    ]
