# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_auto_20160214_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdislike',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='reviewdislike',
            name='user',
        ),
        migrations.AddField(
            model_name='reviewlike',
            name='positive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='reviewDislike',
        ),
    ]
