# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0042_auto_20160214_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='saved',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saved',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
