# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0043_auto_20160214_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ecommerce.media'),
        ),
    ]
