# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-17 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0045_auto_20160314_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('perday', models.PositiveIntegerField(default=0, null=True)),
                ('weeklyDiscount', models.PositiveIntegerField(default=0, null=True)),
                ('monthlyDiscount', models.PositiveIntegerField(default=0, null=True)),
                ('weekend', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
    ]
