# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-18 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0046_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='price',
        ),
    ]
