# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-13 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gitweb', '0006_auto_20160324_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='lastNotified',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 19, 14, 56, 96000, tzinfo=utc)),
        ),
    ]
