# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-13 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gitweb', '0007_repo_lastnotified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='lastNotified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
