# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-18 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gitweb', '0010_auto_20160414_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitnotification',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
