# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitweb', '0012_codecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codecomment',
            name='message',
        ),
        migrations.AddField(
            model_name='codecomment',
            name='text',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
