# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitweb', '0013_auto_20160423_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='codecomment',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gitweb.repo'),
        ),
    ]
