# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitweb', '0014_codecomment_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repopermission',
            name='col1',
            field=models.CharField(default='yes', max_length=32),
        ),
    ]
