# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitweb', '0015_repopermission_col1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repopermission',
            name='col1',
        ),
    ]
