# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitweb', '0017_repo_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='projects.project'),
        ),
    ]
