# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 03:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitweb', '0018_auto_20160501_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repoGroupPermission', to='gitweb.gitGroup'),
        ),
        migrations.AlterField(
            model_name='repo',
            name='groups',
            field=models.ManyToManyField(related_name='repos', to='gitweb.groupPermission'),
        ),
        migrations.AlterField(
            model_name='repo',
            name='perms',
            field=models.ManyToManyField(related_name='repos', to='gitweb.repoPermission'),
        ),
        migrations.AlterField(
            model_name='repopermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repoPermissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
