# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitweb', '0019_auto_20160521_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repoGroupPermissions', to='gitweb.gitGroup'),
        ),
    ]
