# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 03:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitweb', '0020_auto_20160521_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitgroup',
            name='users',
            field=models.ManyToManyField(related_name='gitGroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
