# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virtualWorkforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('sha', models.CharField(max_length=500)),
                ('serverKey', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robotsOwned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
