# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 23:17
from __future__ import unicode_literals

import HR.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainType', models.CharField(choices=[(b'NOT', b'Not selected..'), (b'RND', b'Research and Development'), (b'OPE', b'Operational'), (b'MAN', b'Management')], default=b'NOT', max_length=3)),
                ('domain', models.CharField(choices=[(b'NA', b'Not Assigned'), (b'AUTO', b'Automotive'), (b'SERVICE', b'Service'), (b'RND', b'University'), (b'FMCG', b'FMCG'), (b'POWER', b'Power'), (b'PHARMA', b'Pharmaceuticals'), (b'MANUFAC', b'Manufacturing'), (b'TELE', b'Tele Communications')], default=b'NA', max_length=15)),
                ('unit', models.CharField(max_length=30, null=True)),
                ('department', models.CharField(max_length=30, null=True)),
                ('rank', models.CharField(max_length=8, null=True)),
                ('primaryApprover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approving', to=settings.AUTH_USER_MODEL)),
                ('reportingTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managing', to=settings.AUTH_USER_MODEL)),
                ('secondaryApprover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alsoApproving', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empID', models.PositiveIntegerField(null=True, unique=True)),
                ('displayPicture', models.ImageField(upload_to=HR.models.getDisplayPicturePath)),
                ('dateOfBirth', models.DateField(null=True)),
                ('anivarsary', models.DateField(null=True)),
                ('permanentAddressStreet', models.TextField(blank=True, max_length=100, null=True)),
                ('permanentAddressCity', models.CharField(blank=True, max_length=15, null=True)),
                ('permanentAddressPin', models.IntegerField(blank=True, null=True)),
                ('permanentAddressState', models.CharField(blank=True, max_length=20, null=True)),
                ('permanentAddressCountry', models.CharField(blank=True, max_length=20, null=True)),
                ('localAddressStreet', models.TextField(max_length=100, null=True)),
                ('localAddressCity', models.CharField(max_length=15, null=True)),
                ('localAddressPin', models.IntegerField(null=True)),
                ('localAddressState', models.CharField(max_length=20, null=True)),
                ('localAddressCountry', models.CharField(max_length=20, null=True)),
                ('prefix', models.CharField(choices=[(b'NA', b'NA'), (b'Mr', b'Mr'), (b'Mrs', b'Mrs'), (b'Smt', b'Smt'), (b'Shri', b'Shri')], default=b'NA', max_length=4)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'Other')], default=b'M', max_length=6)),
                ('email', models.EmailField(max_length=50)),
                ('email2', models.EmailField(blank=True, max_length=50)),
                ('mobile', models.PositiveIntegerField(null=True)),
                ('emergency', models.PositiveIntegerField(null=True)),
                ('tele', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('sign', models.ImageField(null=True, upload_to=HR.models.getSignaturesPath)),
                ('IDPhoto', models.ImageField(null=True, upload_to=HR.models.getDisplayPicturePath)),
                ('TNCandBond', models.FileField(null=True, upload_to=HR.models.getTNCandBondPath)),
                ('resume', models.FileField(null=True, upload_to=HR.models.getResumePath)),
                ('certificates', models.FileField(null=True, upload_to=HR.models.getCertificatesPath)),
                ('transcripts', models.FileField(null=True, upload_to=HR.models.getTranscriptsPath)),
                ('otherDocs', models.FileField(blank=True, null=True, upload_to=HR.models.getOtherDocsPath)),
                ('almaMater', models.CharField(max_length=100, null=True)),
                ('pgUniversity', models.CharField(blank=True, max_length=100, null=True)),
                ('docUniversity', models.CharField(blank=True, max_length=100, null=True)),
                ('fathersName', models.CharField(max_length=100, null=True)),
                ('mothersName', models.CharField(max_length=100, null=True)),
                ('wifesName', models.CharField(blank=True, max_length=100, null=True)),
                ('childCSV', models.CharField(blank=True, max_length=100, null=True)),
                ('note1', models.TextField(blank=True, max_length=500, null=True)),
                ('note2', models.TextField(blank=True, max_length=500, null=True)),
                ('note3', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
