# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 23:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='designation',
            name='domainType',
        ),
        migrations.AddField(
            model_name='designation',
            name='managementRank',
            field=models.CharField(choices=[(b'Not Selected..', b'Not Selected..'), (b'Director', b'Director'), (b'Deputy Director', b'Deputy Director'), (b'Manager', b'Manager'), (b'Deputy Manager', b'Deputy Manager'), (b'Executive', b'Executive'), (b'Associate', b'Associate'), (b'General Staff', b'General Staff')], default=b'Not selected..', max_length=3),
        ),
        migrations.AddField(
            model_name='designation',
            name='operationsRank',
            field=models.CharField(choices=[(b'Not Selected..', b'Not Selected..'), (b'Director', b'Director'), (b'Deputy Director', b'Deputy Director'), (b'Manager', b'Manager'), (b'lead', b'lead'), (b'Senior Engineer', b'Senior Engineer'), (b'Engineer', b'Engineer'), (b'Technician', b'Technician'), (b'General Staff', b'General Staff')], default=b'Not selected..', max_length=3),
        ),
        migrations.AddField(
            model_name='designation',
            name='rndRank',
            field=models.CharField(choices=[(b'Not Selected..', b'Not Selected..'), (b'Director', b'Director'), (b'Deputy Director', b'Deputy Director'), (b'Department Head', b'Department Head'), (b'Prof. InCharge', b'Prof. InCharge'), (b'Group Leader', b'Group Leader'), (b'Senior Scientist', b'Senior Scientist'), (b'Scientist', b'Scientist'), (b'Undergraduate Student', b'Undergraduate Student'), (b'Master Student', b'Master Student'), (b'PhD Candidate', b'PhD Candidate'), (b'Post Doctoral Candidate', b'Post Doctoral Candidate'), (b'Senior Engineer', b'Senior Engineer'), (b'Engineer', b'Engineer'), (b'Technician', b'Technician'), (b'General Staff', b'General Staff')], default=b'Not selected..', max_length=3),
        ),
        migrations.AddField(
            model_name='designation',
            name='unitType',
            field=models.CharField(choices=[(b'Not selected..', b'Not selected..'), (b'Research and Development', b'Research and Development'), (b'Operational', b'Operational'), (b'Management', b'Management')], default=b'Not selected..', max_length=3),
        ),
        migrations.AlterField(
            model_name='designation',
            name='domain',
            field=models.CharField(choices=[(b'Not selected..', b'Not selected..'), (b'Automotive', b'Automotive'), (b'Service', b'Service'), (b'University', b'University'), (b'FMCG', b'FMCG'), (b'Power', b'Power'), (b'Pharmaceuticals', b'Pharmaceuticals'), (b'Manufacturing', b'Manufacturing'), (b'Tele Communications', b'Tele Communications')], default=b'Not selected..', max_length=15),
        ),
        migrations.AddField(
            model_name='application',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='HR.module'),
        ),
        migrations.AddField(
            model_name='application',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='appsManaging', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='access',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.application'),
        ),
        migrations.AddField(
            model_name='access',
            name='givenBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvedAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='access',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibleApps', to=settings.AUTH_USER_MODEL),
        ),
    ]
