# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='parent',
        ),
        migrations.AddField(
            model_name='designation',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.rank'),
        ),
    ]
