# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='discription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='discription',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
