# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_accountskey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
