# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_auto_20160103_0808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='groupAccess',
            new_name='groupPermission',
        ),
        migrations.RenameModel(
            old_name='access',
            new_name='permission',
        ),
    ]
