# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_auto_20160515_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='unitType',
            field=models.CharField(choices=[(b'Not selected..', b'Not selected..'), (b'Research and Development', b'Research and Development'), (b'Operations', b'Operations'), (b'Management', b'Management')], default=b'Not selected..', max_length=30),
        ),
    ]
