# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_auto_20160104_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='icon',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='icon',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
