# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_auto_20160104_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettingfield',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='appsettingfield',
            unique_together=set([('name', 'app')]),
        ),
    ]
