# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_auto_20160104_2246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appSettingField',
            new_name='appSettingsField',
        ),
    ]
