# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_auto_20160104_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='canConfigure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canBeConfigureFrom', to='HR.application'),
        ),
    ]
