# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0008_application_canconfigure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettingsfield',
            name='security',
        ),
        migrations.AddField(
            model_name='appsettingsfield',
            name='fieldType',
            field=models.CharField(choices=[(b'flag', b'flag'), (b'value', b'value')], default=b'flag', max_length=5),
        ),
    ]
