# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0009_auto_20160104_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='appsettingsfield',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='discription',
            new_name='description',
        ),
    ]
