# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='shortInfo',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
