# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0002_auto_20160102_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
