# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0004_auto_20160102_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='contentType',
            field=models.CharField(choices=[(b'article', b'article'), (b'tutorial', b'tutorial'), (b'whitepaper', b'whitepaper'), (b'product', b'product')], default=b'article', max_length=15),
        ),
    ]
