# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0005_auto_20151104_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calenderitem',
            old_name='checked',
            new_name='read',
        ),
        migrations.AlterField(
            model_name='calenderitem',
            name='eventType',
            field=models.CharField(choices=[(b'Not Available', b'Not Available'), (b'Meeting', b'Meeting'), (b'Reminder', b'Reminder'), (b'ToDo', b'ToDo'), (b'EVENT', b'EVENT'), (b'Deadline', b'Deadline'), (b'Other', b'Other')], default=b'NONE', max_length=4),
        ),
        migrations.AlterField(
            model_name='calenderitem',
            name='level',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Critical', b'Critical'), (b'Optional', b'Optional'), (b'Mandatory', b'Mandatory')], default=b'NOR', max_length=3),
        ),
        migrations.AlterField(
            model_name='calenderitem',
            name='notification',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PIM.notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='domain',
            field=models.CharField(choices=[(b'System', b'System'), (b'Administration', b'Administration'), (b'Application', b'Application')], default=b'SYS', max_length=3),
        ),
    ]
