# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0006_auto_20151217_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calenderitem',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PIM.notification'),
        ),
    ]
