# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0007_auto_20151217_1930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='calenderItem',
            new_name='calender',
        ),
    ]
