# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0008_auto_20151217_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='calender',
            new_name='calendar',
        ),
    ]
