# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0009_auto_20151217_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='myNotes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
