# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0013_auto_20151223_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='level',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Critical', b'Critical'), (b'Optional', b'Optional'), (b'Mandatory', b'Mandatory')], default=b'Normal', max_length=3),
        ),
    ]
