# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0014_auto_20151223_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='eventType',
            field=models.CharField(choices=[(b'Meeting', b'Meeting'), (b'Reminder', b'Reminder'), (b'ToDo', b'ToDo'), (b'EVENT', b'EVENT'), (b'Deadline', b'Deadline'), (b'Other', b'Other')], default=b'Other', max_length=4),
        ),
    ]
