# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0015_auto_20151224_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
