# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0016_calendar_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='venue',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
