# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0018_auto_20151231_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
