# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 23:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_auto_20160508_0127'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='subTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('notStarted', 'notStarted'), ('inProgress', 'inProgress'), ('stuck', 'stuck'), ('complete', 'complete')], default='notStarted', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('dueDate', models.DateTimeField()),
                ('files', models.ManyToManyField(related_name='tasks', to='projects.media')),
                ('followers', models.ManyToManyField(related_name='taskFollowing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subTasks', to='taskBoard.task'),
        ),
    ]
