# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160508_0127'),
        ('taskBoard', '0003_auto_20160508_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
