# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBoard', '0004_auto_20160508_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.ManyToManyField(null=True, related_name='tasks', to='taskBoard.media'),
        ),
    ]
