# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 03:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gitweb', '0018_auto_20160501_2225'),
        ('taskBoard', '0007_auto_20160508_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='timelineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('message', 'message'), ('git', 'git'), ('file', 'file'), ('system', 'system')], default='message', max_length=50)),
                ('text', models.TextField(max_length=2000, null=True)),
                ('commit', models.ManyToManyField(blank=True, related_name='tasks', to='gitweb.commitNotification')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskBoard.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
