# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitweb', '0018_auto_20160501_2225'),
        ('taskBoard', '0008_timelineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineitem',
            name='commit',
        ),
        migrations.AddField(
            model_name='timelineitem',
            name='commit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='gitweb.commitNotification'),
        ),
    ]
