# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskBoard', '0010_auto_20160511_0626'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timelineitem',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='timelineitem',
            name='commit',
        ),
        migrations.RemoveField(
            model_name='timelineitem',
            name='task',
        ),
        migrations.RemoveField(
            model_name='timelineitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='timelineItem',
        ),
    ]
