# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskBoard', '0012_auto_20160511_1030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timelineitem',
            unique_together=set([]),
        ),
    ]
