# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBoard', '0013_auto_20160511_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
