# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailattachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailAttachments', to=settings.AUTH_USER_MODEL),
        ),
    ]
