# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_proxyaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailAccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
