# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20160523_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxyaccount',
            name='active',
        ),
    ]
